spring:
  datasource:
    url: jdbc:mysql://localhost:3391/emp
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    showsql: true
    hibernate:
      ddl-auto: update